# Generated by Django 4.1.3 on 2022-11-23 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("cpf", models.TextField()),
                ("card", models.TextField()),
                ("hour", models.TimeField()),
                ("shop_owner", models.TextField()),
                ("shop_name", models.TextField()),
            ],
        ),
    ]
