# Generated by Django 4.1.3 on 2022-11-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
    ]
